### ISSUE TITLE
Using new, efficient model and LLH object for out of FoV analysis

### ISSUE THREAD

**Issue by jjd330** [Swift-BAT/NITRATES#10]
The new model, `Sig_Bkg_Model` and new LLH object `LLH_webins2` that were made and merged here #9 , were only applied to the in FoV analysis in script `do_llh_inFoV4realtime2.py` . To apply it to the out of FoV analysis similar changes will need to be made to the script `do_llh_outFoV4realtime2.py`. The changes being using `LLH_webins2` instead of `LLH_webins` and using `Sig_Bkg_Model` instead of the usual compound model to combine the signal and bkg models. Along with the new way to set the bkg and signal parameters.

**Comment by parsotat** [comment]
@jjd330  
In `do_llh_outFoV4realtime2.py`, there isnt quite a one-to-one correspondence between the changes that were made to `do_llh_inFoV4realtime2.py`. It seems like  the changes needs to be:

- LLH_webins -> LLH_webins2
- Changes in the analysis_at_theta_phi function related to using the Sig_Bkg_Model class

Can you take a look at the changes that I made to verify that they are appropriate? The commit to look at is: https://github.com/parsotat/NITRATES/commit/ed5e4a6cc5853843351047d2c492771055a13cfe

**Comment by jjd330** [comment]
Yes, those changes needed to be made. Seems like there's still some changes needed though. Most of L221 - 226 isn't needed anymore. There's now just 1 model parameter ("A"), which can be kept as unfixed. I think you still just need to set the transformation to none, `sig_miner.set_trans(['A'], [None])` . 

You'll need to change `min_at_Epeaks_gammas` too. You'll need to `set_sig_params()` for the Sig_Bkg_Model object at each new spec param.

**Comment by jjd330** [comment]
One other thing that will need to be changed is L235 it gets the background parameters. That will need to be updated to I think, `sig_bkg_mod.set_bkg_params(bkg_bf_params_list[i])` . So you set the bkg params for that specific time bin.

**Comment by parsotat** [comment]
All changes should be complete. As of this commit: https://github.com/parsotat/NITRATES/commit/35a7c44b336850201a2a191a5e04d67e929d07b8 
We still need to test the outFOV response to ensure that things work appropriately.
