### ISSUE TITLE
Speed up job submission process

### ISSUE THREAD

**Issue by jjd330** [Swift-BAT/NITRATES#13]
When jobs are submitted and an ssh connection isn't needed, jobs are submitted one by one which now takes ~5 s each. This needs to either be changed to how jobs are submitted through an ssh connection (minus the ssh part), or submitted as an array. The `-t` arg can be used to submit an array of jobs and there should be some variable name that is iterated for each job and can be used as the job_id. I think this should be supported on the basic cores (it wasn't on the virtual cores). 

This is all in the function sub_jobs in do_manage2.py https://github.com/Swift-BAT/NITRATES/blob/main/do_manage2.py#L801

**Comment by Tohuvavohu** [comment]
Where does the ~5s for each iteration come from? 
[time](https://github.com/Swift-BAT/NITRATES/blob/d6f0727fdc01140045ca8e3e41780e820db0eaf2/do_manage2.py#L907)

**Comment by jjd330** [comment]
Resolved with #14
