### ISSUE TITLE
Read in params from config.json to launch NITRATES

### ISSUE THREAD

**Issue by Tohuvavohu** [Swift-BAT/NITRATES#18]
Need each NITRATES run to have active record of at least the following:

1. Code version (the release tag on Github, no real-time analysis should be run on a non-active release)
2. minDT, maxDT
3. minDur,maxDur
4. BkgPre,BkgPost
5. minSNR
6. Epeaks
7. Gammas

Right now minDur and maxDur are probably the most dynamic of these, need to be set and recorded.
What's the easiest way to do this?

Anything missing to uniquely identify a search configuration?

**Comment by Tohuvavohu** [comment]
Relies on https://github.com/Swift-BAT/UtilityBelt/issues/2

**Comment by Tohuvavohu** [comment]
I think most of this can be handled just with changes to do_manage

**Comment by jjd330** [comment]
For this please look at the changes to how the scripts are called here https://github.com/Swift-BAT/Alfred/commit/ea18b70630c675f12c8679506626ed7ffd123829 . 
The removed args will now need to be found from the claim.json file that will be present in the workdir.

**Comment by jjd330** [comment]
Example contents of a config.json file
{"ERRORS": [], "WARNINGS": [], "config": {"BkgPost": true, "BkgPre": true, "BkgSrcPosFit": null, "Epeaks": [97.7, 212.1, 460.6], "Gammas": [0.1, 0.6, 1.1], "MaxDT": 20.48, "MaxDur": 16.384, "MinDT": -20.48, "MinDur": 0.128, "id": 0, "minSNR": 2.5, "name": "Default", "version": "0.0.0"}, "queueID": 1, "triggerID": 704233771, "trigtime": "2023-04-26T20:28:59.970000"}
