### ISSUE TITLE
Example_LLH_setup_fixed_dirs.ipynb Incorrect import

### ISSUE THREAD

**Issue by parsotat** [Swift-BAT/NITRATES#2]
In the Example_LLH_setup_fixed_dirs.ipynb there is a block that states:

```
from do_manage import im_dist
```

this gives an error since there is no file in the package with this name. Instead there is a file called do_manage2. Should the line instead be:
```
from do_manage2 import im_dist
```
Thanks!

**Comment by parsotat** [comment]
if the line should be 
```
from do_manage2 import im_dist
```
Then I get a separate error that states: 
```
No module named 'paramiko'
```

**Comment by jjd330** [comment]
I moved a bunch of old files to the archive folder and I guess I didn't test well at all if some were still being called. 
I'll make some quick fixes so that the notebook should be able to run.

**Comment by Tohuvavohu** [comment]
And yes, paramiko is a dependency (but only for submitting jobs to the cluster)

**Comment by jjd330** [comment]
The last 2 commits should fix that issue. Changed it to import do_manage2 and made the paramiko import optional. 
Let me know if you run into more issues here.

**Comment by parsotat** [comment]
The other issue that I am running into is the location of the work directory in the 5th block of the Jupiter notebook. There is a work directory that seems to include an SQL database which is not included in the repo. As a result, it tries to read data from a non-existent SQL database. Along this train of thought, are the SQL databases implemented here to hold observational database because that is what is produced in the BAT-GUANO pipeline?

Also, as an aside, the following code can be used to modify the import statements at the start of helper_funcs.py to make the import statements compatible with python 2 and 3 (I am currently running the code with python3):
```
import smtplib
import sys
from email.mime.text import MIMEText
if sys.version_info < (3, 0):
    from email.MIMEMultipart import MIMEMultipart
else:
    from email.mime.multipart import MIMEMultipart
    
if sys.version_info < (3, 0):
    from email.MIMEBase import MIMEBase
else:
    from email.mime.base import MIMEBase
    
if sys.version_info < (3, 0):
    from email import Encoders
else:
    from email import encoders
```

**Comment by Tohuvavohu** [comment]
re: the python3 ifying of helper_funcs.py 
Awesome! you can submit a pull request with this change or wait with what (im sure) will be more changes for python3 compatability that you find and then submit a PR.

i'll let jimmy comment on the DB issue.

**Comment by jjd330** [comment]
The notebook was meant to use data that's in a directory on the Penn State cluster, which sorry I totally forgot to mention when you started trying to run this. I'll upload that directory to the repo with the data needed to run the notebook so it can be run once the response files are also set to be used. 
Also once you get to cell 11 you will need the response files that are on Zenodo. You'll need to download them, untar them (they're a few hundred GBs untarred), and point to the correct directories where they are in the code. The `RayTraces` object can be given the directory where the ray trace files are, but the other response directories are still hardcoded in `response.py` and `models.py`

For the sqlite DB, the DB only holds a few things like the trigger time. In the early stages of the search it held results, but the cluster's file system did not like that many jobs writing to a sqlite DB at the same time. 
There are separate DBs that aren't used in the likelihood analysis at all, but are where the web scraping for data stores the urls, file names, start, stop times of event and attitude files.

**Comment by jjd330** [comment]
The F646018360 directory has been added. So you should be able to at least get to cell 10 now.

**Comment by parsotat** [comment]
Thanks for that insight @jjd330. I think that using  hdf5, for example, would help circumvent the issue of multiple processes writing to the same file. That can be something that we incorporate later on to hold a variety of information related to the NITRATES inputs and results for a given run.

Focusing on the Jupiter notebook, I am not getting stuck on block 11. Where, after I changed some of the paths necessary for the code to find my response files, the code is trying to find the file: /storage/work/jjd330/local/bat_data/OutFoVbursts/GRB131014A/flor_Aeff_adjust.npz 
which does not seem to be a part of the GitHub repo. 

Also, looking through the hardcoded directories in the config.py file, I see other directories that are not included in the repo that may play a role later on in the Jupiter notebook. these are:
- /storage/work/jjd330/local/bat_data/BatML/
- /gpfs/scratch/jjd330/bat_data/footprints_npy/
- /storage/work/jjd330/local/bat_data/drms/
- /gpfs/scratch/jjd330/bat_data/drms4quads/

**Comment by jjd330** [comment]
Thanks for looking into those @parsotat . Some of those are old and not used anymore, so I should probably just go through my self and try to remove old paths like that and add clear to understand args in the main objects to give the path to responses like I do for the RayTraces class. I can do that after the Thanksgiving break. 
I'm pretty sure flor_Aeff_adjust.npz is not used anymore, so I'll take that part out. 

Yeah, hdf5 might be a good option if it works well on the file system (gpfs). That will be nice to try in the future. I tried sqlite DBs then kinda gave up on having the jobs be able to communicate with each other.

**Comment by parsotat** [comment]
no problem @jjd330, let me know when things are updated so I can pull any changes that are made. 

As for HDF5, that works across a number of file systems and it is a very robust data format that allows multiple processes to write to a given file. This is something that can be easily incorporated in future versions of the code that are geared towards performance improvements.

**Comment by jjd330** [comment]
Ok, just committed the updates. 
I've updated `config.py`, so that if all of the response files are in the directory `NITRATES_RESP_DIR` it should be able to give the full path to them. Where `NITRATES_RESP_DIR` is either set as an env variable or hardcoded into `config.py`. 
I also updated some of the main objects to by default get the resp path from `config.py` or take the path as an argument, and updated the example notebook to use this updated way of getting the resp paths. 
I've added a description of what files are needed and where to get them to the README. 
Let me know if my explanations in the README or in the notebook comments aren't clear. 

The example notebook should now work in Python2 if all the necessary response files are there. I've been able to run it in a new Python2 env on my laptop. For Python3, I think I fixed all of the print statements that would keep you from importing packages, but I still don't think the whole notebook will be able to run. I've just realized that I use iteritems() often with dictionaries, which is no longer a thing in Python3. So, that's most recent error I got up to while trying to run it in Python3.

**Comment by parsotat** [comment]
Thanks for the update. I have gotten past the use of iteritems() and have run into an error in cell 17 that states:

```AttributeError: 'ResponseInFoV2' object has no attribute 'comp_flor_resp_dpis'```

This error seems to be related to the fact that the method ```calc_tot_resp_dpis()``` is not called. When I try to execute: 
```sig_mod.resp_obj.get_comp_flor_resp_dpis()``` I get the same error as above.

Another error that has popped up when I try to restart the Jupiter notebook kernel and run the cells (in an effort to debug the above error) is that the notebook produces an error at cell 12. This error seems to be more complicated and is as follows:
```
~/Documents/BAT_SCRIPTS/NITRATES/NITRATES_PY3/models.py in set_theta_phi(self, theta, phi)
   3326             self._trans_theta = theta
   3327             self._trans_phi = phi
-> 3328             self.resp_obj.set_theta_phi(theta, phi)
   3329 
   3330         elif ang_sep(phi, 90.0-theta, self._trans_phi, 90.0-self._trans_theta) > self._trans_update:

~/Documents/BAT_SCRIPTS/NITRATES/NITRATES_PY3/response.py in set_theta_phi(self, theta, phi)
   1713         self.mask_trans = self.mask_obj.get_trans()
   1714 
-> 1715         self.full_struct.set_theta_phi(np.radians(theta), np.radians(phi))
   1716         self._lines_trans_dpis = self.full_struct.get_trans()
   1717         self.lines_trans_dpis = self._lines_trans_dpis*self.mask_trans

~/Documents/BAT_SCRIPTS/NITRATES/NITRATES_PY3/StructClasses.py in set_theta_phi(self, theta, phi)
    569         self.phi = phi
    570         for name, struct in self.struct_dict.items():
--> 571             struct.set_theta_phi(theta, phi)
    572 
    573         if hasattr(self, 'energy'):

~/Documents/BAT_SCRIPTS/NITRATES/NITRATES_PY3/StructClasses.py in set_theta_phi(self, theta, phi)
    310         self.angs2norm = self.shield_obj.get_angs2norm(self.theta, self.phi)
    311 
--> 312         self.calc_dists()
    313         if hasattr(self, 'energy'):
    314             self.calc_tot_rhomu_dist()

~/Documents/BAT_SCRIPTS/NITRATES/NITRATES_PY3/StructClasses.py in calc_dists(self)
    330                     self.dists[i][poly_bl] = 0.0
    331                 continue
--> 332             poly = self.shield_obj.get_poly(polyid)
    333             layer = self.shield_obj.shield_layer[polyid]
    334             base_dists = self.ds_base[layer]

~/Documents/BAT_SCRIPTS/NITRATES/NITRATES_PY3/shield_structure.py in get_poly(self, ident)
    776         else:
    777             name = ident
--> 778         return self.shield_struct.shield_dict[name]
    779 
    780     def does_intersect_poly(self, theta, phi, x, y, z, ident):

KeyError: 23
```

If you have any insights on this issue that would be extremely helpful.

**Comment by jjd330** [comment]
`calc_tot_resp_dpis()` is called when theta and phi is set with `set_theta_phi()` in cell 12, so my guess would be that cell 12 didn't work the first time you went through too and for some reason the error wasn't reported well. 

For the error in cell 12, I'm not exactly sure what's happening. If you look at `Shield_Interactions.get_poly(self, ident)` in `shield_structure.py`, `name` shouldn't be an int. If it's an int or a float then it gets the shield name from a list of strings. Did you change anything around there that could change that? I'm pretty sure the code there should still work the same in Python3.

**Comment by parsotat** [comment]
I have tried running the print statement and I got:
``` ['00', 'A01', 'A02', 'A03', 'Ba01', 'Ba01flip', 'Ba02', 'Ba02flip', 'Ba03', 'Ba03flip', 'Bb01', 'Bb01flip', 'Bb02', 'Bb02flip', 'Bb03', 'Bb03flip', 'Bc01', 'Bc01flip', 'Bc02', 'Bc02flip', 'Bc03', 'Bc03flip', 'C01', 'C02', 'C03', 'D01', 'D01flip', 'D02', 'D02flip', 'D03', 'D03flip'] ```

The only changes that I have made to allow the code to run with python3 is in StructClasses.py where I changed all the *.iteritems() to list(*.items()) which I wouldn't expect to affect anything. Im sure that this issue doesn't occur when you run the notebook with python2 so it must be something related to python3.

**Comment by jjd330** [comment]
Hm, yeah I'm really not sure what's happening then. The `.get_poly()` function is just this
```
    def get_poly(self, ident):
        '''
        ident is either the name as a string or
        the id (the list index) as an int
        '''

        if isinstance(ident, int) or isinstance(ident, float):
            name = self.shield_struct.shield_names[int(ident)]
        else:
            name = ident
        return self.shield_struct.shield_dict[name]
```

`polyid` in your traceback should be an int and given as the `ident` arg, and it seems like it's 23 since it says `Key Error: 23`. If 23 is the arg then the if statement should be true and it should get `name` from the `shield_names` list. I don't know how an integer gets past that if statement. 

It did work fine for my in python2, and it doesn't seem like your changes could effect this at all.

**Comment by parsotat** [comment]
I think that I have identified why the integer gets past the if statement. 

The value of 23 (which comes from ```sig_mod.resp_obj.full_struct.struct_dict['Shield'].poly_ids2use```) that is passed to the method is actually a <class 'numpy.int64'> object in python3 which isn't an instance of int, and thus bypasses the if statement. 

I will try to figure out a modification that will prevent this from happening.

**Comment by jjd330** [comment]
Oh, good catch! I was only trying with a regular int in python3 and forgot about numpy stuff.

**Comment by parsotat** [comment]
I added ```or isinstance(ident, np.integer)``` to the if statement in the function get_poly() in shield_structure.py and things seem to work well now. I am able to run through the whole notebook now. 

Thanks for the help!

**Comment by jjd330** [comment]
Woo, awesome! No problem
I guess I'll close this issue now then, and as other issues come up else where you can submit a new issue.
