### ISSUE TITLE
Example_Reading_Results Notebook Error

### ISSUE THREAD

**Issue by parsotat** [Swift-BAT/NITRATES#3]
When running the Example_Reading_Results.ipynb, I run into an error in the 13th cell where the function ```get_rate_res_fnames()``` is not finding any files with 'rates' in the name. It is searching in the F646018360/ directory and there are none of these files in the repo. Are they supposed to be there or included with the Zenodo data files?

**Comment by jjd330** [comment]
I only put the data necessary to run the other notebook in that directory. All of the result files from the search are a few thousand files and I think a few hundred MBs, so I'll see tomorrow if I'm able to add those to the repo. I might need to tar them. I'll update here once I've added them.

**Comment by jjd330** [comment]
Just added the search results for F646018360 as a tarred file. So you'll just need to untar `F646018360_results.tar.gz` and the `get_*_res_fnames()` functions should work.

**Comment by parsotat** [comment]
Great, thanks A TON @jjd330. The notebook is able to be fully run now.
