### ISSUE TITLE
Identifying when there's no good data during the signal time window

### ISSUE THREAD

**Issue by jjd330** [Swift-BAT/NITRATES#38]
Currently NITRATES only identifies when there's no good data at all in the file (usually because of slewing). If there's not enough good data for the bkg, the bkg job will just fail and if there's no good time during the signal time window (+/- 20 s) then do_full_rates will just fail. These should be identified by do_manage and reported to echo

**Comment by Tohuvavohu** [comment]
@jjd330 
If do_manage isn't launching if time_seeds.csv isn't created, then i can't manage this from inside do_manage.
should i report from do_full_rates?
thoughts?

**Comment by Tohuvavohu** [comment]
should it just be here in this else clause? https://github.com/Swift-BAT/NITRATES/blob/22d5d96da878bde51af1810aad6601d153a557e0/nitrates/analysis_seeds/do_full_rates.py#L599

**Comment by jjd330** [comment]
THat would be good to report that there's no rate seeds, but it won't catch errors or if there's no signal window time. Here is where the error happens and the script dies https://github.com/Swift-BAT/NITRATES/blob/22d5d96da878bde51af1810aad6601d153a557e0/nitrates/analysis_seeds/do_full_rates.py#L550 . You can add a try statement around that and report it there or I can try to handle this better (try to have it fail less often and just report if there's no signal window data instead of just trying and failing)

**Comment by Tohuvavohu** [comment]
Should i report that there's no rates seeds? or will this be caught elsewhere?

**Comment by jjd330** [comment]
Probably a good idea to report it. Right now nitrates just goes to submit split rates jobs that fail because there's no seeds to process

**Comment by Tohuvavohu** [comment]
hmm, how should EchoLocation display this to the user?
I haven't considered this before, nitrates 'runs' but there are just no time seeds...

**Comment by jjd330** [comment]
Not sure. I guess the most important thing is that it gets marked complete.
