### ISSUE TITLE
do_data_setup keeps going even if no data

### ISSUE THREAD

**Issue by Tohuvavohu** [Swift-BAT/NITRATES#39]
Issue is here https://github.com/Swift-BAT/NITRATES/blob/22d5d96da878bde51af1810aad6601d153a557e0/nitrates/data_prep/do_data_setup.py#L762 
doesn't throw a failure, so it keeps going.

Proposed solution is instead to test
`if evfname or dmask or acs_tab files do not exist:
    report to echo
    return out of function
`

confirm @jjd330 ?

**Comment by jjd330** [comment]
Yep, that's correct.

**Comment by Tohuvavohu** [comment]
@jjd330 
should i still put this in here? or put report back to Echo in Alfred now that using guano api?

**Comment by jjd330** [comment]
I guess in Alfred now. Do_data_setup should still work but you'd have to wait for both scripts to time out then

**Comment by Tohuvavohu** [comment]
hmmm. Should we change the way do_data_setup works now then?

**Comment by jjd330** [comment]
I guess we don't need it to wait for data anymore if we're relying on alfred to find the data. At least if where the data is is specified in the args, like it is now
